p8105\_hw2\_sc4935
================
Shiwei Chen
10/2/2021

# Problem 1

We first import `Trash-Wheel-Collection-Totals-8-6-19.xlsx`.

Omit non-data entries.

``` r
TrashWheel_df = read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "Mr. Trash Wheel", skip = 1, range = "A2:N535") %>% 
  janitor::clean_names() %>% 
  drop_na()

names(TrashWheel_df)
```

    ##  [1] "dumpster"           "month"              "year"              
    ##  [4] "date"               "weight_tons"        "volume_cubic_yards"
    ##  [7] "plastic_bottles"    "polystyrene"        "cigarette_butts"   
    ## [10] "glass_bottles"      "grocery_bags"       "chip_bags"         
    ## [13] "sports_balls"       "homes_powered"

``` r
view(TrashWheel_df)

TrashWheel_df
```

    ## # A tibble: 453 × 14
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##    <chr>    <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1 1        May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2 2        May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3 3        May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4 4        May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5 5        May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6 6        May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7 7        May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8 8        May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9 9        June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10 10       June   2014 2014-06-11 00:00:00        3.76                 18
    ## # … with 443 more rows, and 8 more variables: plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, sports_balls <dbl>,
    ## #   homes_powered <dbl>

Then, to omit rows that do not include dumpster-specific data, and round
the number of sports balls to the nearest integer.

``` r
TrashWheel_cleaned_df = 
  filter(TrashWheel_df, !is.na(dumpster)) %>%
  mutate(sports_balls = round(sports_balls, digits = 0))

view(TrashWheel_cleaned_df)
TrashWheel_cleaned_df
```

    ## # A tibble: 453 × 14
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##    <chr>    <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1 1        May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2 2        May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3 3        May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4 4        May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5 5        May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6 6        May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7 7        May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8 8        May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9 9        June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10 10       June   2014 2014-06-11 00:00:00        3.76                 18
    ## # … with 443 more rows, and 8 more variables: plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, sports_balls <dbl>,
    ## #   homes_powered <dbl>

Read and clean precipitation data for 2018 and 2019.

``` r
P18_df = 
  read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "2018 Precipitation", skip = 1, range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(total)) %>% 
  mutate(year = 2018)

P18_df
```

    ## # A tibble: 12 × 3
    ##    month total  year
    ##    <dbl> <dbl> <dbl>
    ##  1     1  0.94  2018
    ##  2     2  4.8   2018
    ##  3     3  2.69  2018
    ##  4     4  4.69  2018
    ##  5     5  9.27  2018
    ##  6     6  4.77  2018
    ##  7     7 10.2   2018
    ##  8     8  6.45  2018
    ##  9     9 10.5   2018
    ## 10    10  2.12  2018
    ## 11    11  7.82  2018
    ## 12    12  6.11  2018

``` r
P19_df = 
  read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "2019 Precipitation", skip = 1, range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(total)) %>% 
  mutate(year = 2019)

P19_df
```

    ## # A tibble: 12 × 3
    ##    month total  year
    ##    <dbl> <dbl> <dbl>
    ##  1     1  3.1   2019
    ##  2     2  3.64  2019
    ##  3     3  4.47  2019
    ##  4     4  1.46  2019
    ##  5     5  3.58  2019
    ##  6     6  0.42  2019
    ##  7     7  3.85  2019
    ##  8     8  2.39  2019
    ##  9     9  0.16  2019
    ## 10    10  5.45  2019
    ## 11    11  1.86  2019
    ## 12    12  3.57  2019

Combine precipitation datasets, convert month to a character variable.

``` r
P1819_df = full_join(P18_df, P19_df) %>% 
  mutate(month = month.name[month]) %>% 
  relocate(year)
```

    ## Joining, by = c("month", "total", "year")

``` r
view(P1819_df)
P1819_df  
```

    ## # A tibble: 24 × 3
    ##     year month     total
    ##    <dbl> <chr>     <dbl>
    ##  1  2018 January    0.94
    ##  2  2018 February   4.8 
    ##  3  2018 March      2.69
    ##  4  2018 April      4.69
    ##  5  2018 May        9.27
    ##  6  2018 June       4.77
    ##  7  2018 July      10.2 
    ##  8  2018 August     6.45
    ##  9  2018 September 10.5 
    ## 10  2018 October    2.12
    ## # … with 14 more rows

Write a paragraph about these data.

``` r
Sportsballs_19 = filter(TrashWheel_cleaned_df, year == 2019) %>% 
  select(sports_balls)

median(pull(Sportsballs_19, sports_balls))
```

    ## [1] 9

``` r
sum(pull(P18_df, total))
```

    ## [1] 70.33

``` r
skimr::skim(TrashWheel_df)
```

|                                                  |                |
|:-------------------------------------------------|:---------------|
| Name                                             | TrashWheel\_df |
| Number of rows                                   | 453            |
| Number of columns                                | 14             |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |                |
| Column type frequency:                           |                |
| character                                        | 2              |
| numeric                                          | 11             |
| POSIXct                                          | 1              |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                |
| Group variables                                  | None           |

Data summary

**Variable type: character**

| skim\_variable | n\_missing | complete\_rate | min | max | empty | n\_unique | whitespace |
|:---------------|-----------:|---------------:|----:|----:|------:|----------:|-----------:|
| dumpster       |          0 |              1 |   1 |   3 |     0 |       453 |          0 |
| month          |          0 |              1 |   3 |   9 |     0 |        13 |          0 |

**Variable type: numeric**

| skim\_variable       | n\_missing | complete\_rate |     mean |       sd |      p0 |     p25 |      p50 |      p75 |      p100 | hist  |
|:---------------------|-----------:|---------------:|---------:|---------:|--------:|--------:|---------:|---------:|----------:|:------|
| year                 |          0 |              1 |  2017.26 |     1.95 | 2014.00 | 2015.00 |  2018.00 |  2019.00 |   2021.00 | ▆▃▇▃▃ |
| weight\_tons         |          0 |              1 |     3.20 |     0.73 |    0.78 |    2.72 |     3.19 |     3.68 |      5.62 | ▁▃▇▃▁ |
| volume\_cubic\_yards |          0 |              1 |    15.41 |     1.48 |    7.00 |   15.00 |    15.00 |    15.00 |     20.00 | ▁▁▁▇▂ |
| plastic\_bottles     |          0 |              1 |  1898.93 |  1027.78 |  210.00 |  980.00 |  1850.00 |  2640.00 |   5960.00 | ▇▇▅▁▁ |
| polystyrene          |          0 |              1 |  1920.92 |  1161.89 |  210.00 |  950.00 |  1650.00 |  2730.00 |   6540.00 | ▇▅▃▁▁ |
| cigarette\_butts     |          0 |              1 | 24521.68 | 32047.72 |  980.00 | 5000.00 | 11000.00 | 32000.00 | 310000.00 | ▇▁▁▁▁ |
| glass\_bottles       |          0 |              1 |    22.45 |    17.44 |    0.00 |    9.00 |    18.00 |    32.00 |    110.00 | ▇▃▂▁▁ |
| grocery\_bags        |          0 |              1 |  1103.82 |   860.26 |   50.00 |  425.00 |   820.00 |  1620.00 |   3750.00 | ▇▅▂▂▁ |
| chip\_bags           |          0 |              1 |  1558.40 |   946.59 |  180.00 |  800.00 |  1327.00 |  2150.00 |   5085.00 | ▇▆▃▁▁ |
| sports\_balls        |          0 |              1 |    11.75 |     9.18 |    0.00 |    5.20 |     9.00 |    16.00 |     56.00 | ▇▃▁▁▁ |
| homes\_powered       |          0 |              1 |    45.32 |    21.71 |    0.00 |   38.83 |    51.17 |    58.67 |     93.67 | ▃▂▇▅▁ |

**Variable type: POSIXct**

| skim\_variable | n\_missing | complete\_rate | min        | max        | median     | n\_unique |
|:---------------|-----------:|---------------:|:-----------|:-----------|:-----------|----------:|
| date           |          0 |              1 | 1900-01-20 | 2021-01-04 | 2018-02-05 |       275 |

``` r
skimr::skim(TrashWheel_cleaned_df)
```

|                                                  |                         |
|:-------------------------------------------------|:------------------------|
| Name                                             | TrashWheel\_cleaned\_df |
| Number of rows                                   | 453                     |
| Number of columns                                | 14                      |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |                         |
| Column type frequency:                           |                         |
| character                                        | 2                       |
| numeric                                          | 11                      |
| POSIXct                                          | 1                       |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                         |
| Group variables                                  | None                    |

Data summary

**Variable type: character**

| skim\_variable | n\_missing | complete\_rate | min | max | empty | n\_unique | whitespace |
|:---------------|-----------:|---------------:|----:|----:|------:|----------:|-----------:|
| dumpster       |          0 |              1 |   1 |   3 |     0 |       453 |          0 |
| month          |          0 |              1 |   3 |   9 |     0 |        13 |          0 |

**Variable type: numeric**

| skim\_variable       | n\_missing | complete\_rate |     mean |       sd |      p0 |     p25 |      p50 |      p75 |      p100 | hist  |
|:---------------------|-----------:|---------------:|---------:|---------:|--------:|--------:|---------:|---------:|----------:|:------|
| year                 |          0 |              1 |  2017.26 |     1.95 | 2014.00 | 2015.00 |  2018.00 |  2019.00 |   2021.00 | ▆▃▇▃▃ |
| weight\_tons         |          0 |              1 |     3.20 |     0.73 |    0.78 |    2.72 |     3.19 |     3.68 |      5.62 | ▁▃▇▃▁ |
| volume\_cubic\_yards |          0 |              1 |    15.41 |     1.48 |    7.00 |   15.00 |    15.00 |    15.00 |     20.00 | ▁▁▁▇▂ |
| plastic\_bottles     |          0 |              1 |  1898.93 |  1027.78 |  210.00 |  980.00 |  1850.00 |  2640.00 |   5960.00 | ▇▇▅▁▁ |
| polystyrene          |          0 |              1 |  1920.92 |  1161.89 |  210.00 |  950.00 |  1650.00 |  2730.00 |   6540.00 | ▇▅▃▁▁ |
| cigarette\_butts     |          0 |              1 | 24521.68 | 32047.72 |  980.00 | 5000.00 | 11000.00 | 32000.00 | 310000.00 | ▇▁▁▁▁ |
| glass\_bottles       |          0 |              1 |    22.45 |    17.44 |    0.00 |    9.00 |    18.00 |    32.00 |    110.00 | ▇▃▂▁▁ |
| grocery\_bags        |          0 |              1 |  1103.82 |   860.26 |   50.00 |  425.00 |   820.00 |  1620.00 |   3750.00 | ▇▅▂▂▁ |
| chip\_bags           |          0 |              1 |  1558.40 |   946.59 |  180.00 |  800.00 |  1327.00 |  2150.00 |   5085.00 | ▇▆▃▁▁ |
| sports\_balls        |          0 |              1 |    11.75 |     9.18 |    0.00 |    5.00 |     9.00 |    16.00 |     56.00 | ▇▃▁▁▁ |
| homes\_powered       |          0 |              1 |    45.32 |    21.71 |    0.00 |   38.83 |    51.17 |    58.67 |     93.67 | ▃▂▇▅▁ |

**Variable type: POSIXct**

| skim\_variable | n\_missing | complete\_rate | min        | max        | median     | n\_unique |
|:---------------|-----------:|---------------:|:-----------|:-----------|:-----------|----------:|
| date           |          0 |              1 | 1900-01-20 | 2021-01-04 | 2018-02-05 |       275 |

``` r
skimr::skim(P1819_df)
```

|                                                  |           |
|:-------------------------------------------------|:----------|
| Name                                             | P1819\_df |
| Number of rows                                   | 24        |
| Number of columns                                | 3         |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |           |
| Column type frequency:                           |           |
| character                                        | 1         |
| numeric                                          | 2         |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |           |
| Group variables                                  | None      |

Data summary

**Variable type: character**

| skim\_variable | n\_missing | complete\_rate | min | max | empty | n\_unique | whitespace |
|:---------------|-----------:|---------------:|----:|----:|------:|----------:|-----------:|
| month          |          0 |              1 |   3 |   9 |     0 |        12 |          0 |

**Variable type: numeric**

| skim\_variable | n\_missing | complete\_rate |    mean |   sd |      p0 |     p25 |     p50 |     p75 |    p100 | hist  |
|:---------------|-----------:|---------------:|--------:|-----:|--------:|--------:|--------:|--------:|--------:|:------|
| year           |          0 |              1 | 2018.50 | 0.51 | 2018.00 | 2018.00 | 2018.50 | 2019.00 | 2019.00 | ▇▁▁▁▇ |
| total          |          0 |              1 |    4.34 | 2.88 |    0.16 |    2.32 |    3.74 |    5.62 |   10.47 | ▇▇▇▂▃ |

In conclusion, the total precipitation in 2018 is 70.33, and the median
number of sports balls in a dumpster in 2019 is 9. We omit some non-data
columns and rows to clean the Trash Wheel data set. For example, we
round the variable of “number of sports balls” to integer. For the 2018
and 2019 Precipitation combined data set, I suppose that the key
variable is “total”, since it illustrates the monthly precipitation
value for both 2018 and 2019.

# Problem 2

We first import the FiveThirtyEight data.

First, clean the data in pols-month.csv.

``` r
pols_month_df = read_csv("./data/pols-month.csv") %>% 
  janitor::clean_names() %>%
  separate(mon, into = c("year", "month", "day"), sep = "-") %>%
  mutate(month = month.name[as.numeric(month)]) %>% 
  rename(gop = prez_gop, dem = prez_dem) %>% 
  pivot_longer(
    c(gop, dem),
    names_to = "president", 
    values_to = "win") %>%
  filter(!win == 0) %>% 
  select(-day, -win) %>% 
  view()
```

    ## Rows: 822 Columns: 9

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pols_month_df
```

    ## # A tibble: 822 × 9
    ##    year  month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <chr> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1 1947  January        23      51     253      23      45     198 dem      
    ##  2 1947  February       23      51     253      23      45     198 dem      
    ##  3 1947  March          23      51     253      23      45     198 dem      
    ##  4 1947  April          23      51     253      23      45     198 dem      
    ##  5 1947  May            23      51     253      23      45     198 dem      
    ##  6 1947  June           23      51     253      23      45     198 dem      
    ##  7 1947  July           23      51     253      23      45     198 dem      
    ##  8 1947  August         23      51     253      23      45     198 dem      
    ##  9 1947  September      23      51     253      23      45     198 dem      
    ## 10 1947  October        23      51     253      23      45     198 dem      
    ## # … with 812 more rows

Second, clean the data in snp.csv using a similar process to the above.

``` r
snp_df = read_csv("./data/snp.csv") %>% 
  janitor::clean_names() %>%
  separate(date, into = c("month", "day", "year"), sep = "/") %>% 
  relocate(year)
```

    ## Rows: 787 Columns: 2

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp20_df = filter(snp_df, year <= 15) %>% 
  mutate(year = as.numeric(year) + 2000)
snp19_df = filter(snp_df, year >= 16) %>% 
  mutate(year = as.numeric(year) + 1900)

snp_df_final = bind_rows(snp20_df, snp19_df) %>% 
  mutate(year = as.character(year)) %>% 
  mutate(month = month.name[as.numeric(month)]) %>% 
  select(-day) %>% 
  view()
  
snp_df_final
```

    ## # A tibble: 787 × 3
    ##    year  month    close
    ##    <chr> <chr>    <dbl>
    ##  1 2015  July     2080.
    ##  2 2015  June     2063.
    ##  3 2015  May      2107.
    ##  4 2015  April    2086.
    ##  5 2015  March    2068.
    ##  6 2015  February 2104.
    ##  7 2015  January  1995.
    ##  8 2014  December 2059.
    ##  9 2014  November 2068.
    ## 10 2014  October  2018.
    ## # … with 777 more rows

Third, tidy the unemployment data so that it can be merged with the
previous datasets.

``` r
unemp_df = read_csv("./data/unemployment.csv") %>% 
  pivot_longer(
    Jan:Dec,
    names_to = "month", 
    values_to = "unemployment_rate") %>% 
  janitor::clean_names() %>% 
  mutate(month = month.name[match(month,month.abb)]) %>% 
  mutate(year = as.character(year)) %>% 
  view()
```

    ## Rows: 68 Columns: 13

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemp_df  
```

    ## # A tibble: 816 × 3
    ##    year  month     unemployment_rate
    ##    <chr> <chr>                 <dbl>
    ##  1 1948  January                 3.4
    ##  2 1948  February                3.8
    ##  3 1948  March                   4  
    ##  4 1948  April                   3.9
    ##  5 1948  May                     3.5
    ##  6 1948  June                    3.6
    ##  7 1948  July                    3.6
    ##  8 1948  August                  3.9
    ##  9 1948  September               3.8
    ## 10 1948  October                 3.7
    ## # … with 806 more rows

Merge above datasets.

``` r
merged_df = left_join(pols_month_df, snp_df_final)
```

    ## Joining, by = c("year", "month")

``` r
merged_df_final = left_join(merged_df, unemp_df) %>% 
  view()
```

    ## Joining, by = c("year", "month")

``` r
merged_df_final
```

    ## # A tibble: 822 × 11
    ##    year  month   gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <chr> <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1 1947  January      23      51     253      23      45     198 dem          NA
    ##  2 1947  Februa…      23      51     253      23      45     198 dem          NA
    ##  3 1947  March        23      51     253      23      45     198 dem          NA
    ##  4 1947  April        23      51     253      23      45     198 dem          NA
    ##  5 1947  May          23      51     253      23      45     198 dem          NA
    ##  6 1947  June         23      51     253      23      45     198 dem          NA
    ##  7 1947  July         23      51     253      23      45     198 dem          NA
    ##  8 1947  August       23      51     253      23      45     198 dem          NA
    ##  9 1947  Septem…      23      51     253      23      45     198 dem          NA
    ## 10 1947  October      23      51     253      23      45     198 dem          NA
    ## # … with 812 more rows, and 1 more variable: unemployment_rate <dbl>

Write a short paragraph about these datasets.

``` r
dim(merged_df_final)
```

    ## [1] 822  11

``` r
range(merged_df_final$year)
```

    ## [1] "1947" "2015"

``` r
names(merged_df_final)
```

    ##  [1] "year"              "month"             "gov_gop"          
    ##  [4] "sen_gop"           "rep_gop"           "gov_dem"          
    ##  [7] "sen_dem"           "rep_dem"           "president"        
    ## [10] "close"             "unemployment_rate"

In conclusion, the dataset of pols-month contains 9 variables, and
illustrate the number of national politicians who are democratic or
republican. In this datadet, we combine two variables, prez\_gop and
prez\_dem, which shows whether the president was republican on the
associated date clearly. For dataset of snp, it contains 2 variables,
date and the closing values of the S&P stock index on the associated
date. For unemployment dataset, it presents the monthly unemployment
rate start on 1948.

For the resulting dataset, the dimention is 822 and 11, which implies
822 rows and 11 columns, the range of year from 1947 to 2015, and there
are some key variables, like year, month, president, close, and
unemployment\_rate. From original dataset, the date variable is
seperated to year and month. President shows whether he is democratic or
republican. Close and unemployment\_rate are 2 most important value to
reflect the society.

# Problem 3

We first import the data of the popularity of baby names.

Load and tidy the data, and remove duplicate rows.

``` r
popular_baby_names_df = read_csv("./data/Popular_Baby_Names.csv") %>% 
  janitor::clean_names() %>% 
  mutate(ethnicity = recode(ethnicity, "ASIAN AND PACI" = "ASIAN AND PACIFIC ISLANDER", "WHITE NON HISP" = "WHITE NON HISPANIC", "BLACK NON HISP" = "BLACK NON HISPANIC")) %>% 
  mutate(gender = str_to_sentence(gender),
         ethnicity = str_to_sentence(ethnicity),
         childs_first_name = str_to_sentence(childs_first_name)) %>% 
  mutate(year_of_birth = as.character(year_of_birth)) %>% 
  distinct() %>% 
  view()
```

    ## Rows: 19418 Columns: 6

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Gender, Ethnicity, Child's First Name
    ## dbl (3): Year of Birth, Count, Rank

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
popular_baby_names_df
```

    ## # A tibble: 12,181 × 6
    ##    year_of_birth gender ethnicity                  childs_first_name count  rank
    ##    <chr>         <chr>  <chr>                      <chr>             <dbl> <dbl>
    ##  1 2016          Female Asian and pacific islander Olivia              172     1
    ##  2 2016          Female Asian and pacific islander Chloe               112     2
    ##  3 2016          Female Asian and pacific islander Sophia              104     3
    ##  4 2016          Female Asian and pacific islander Emily                99     4
    ##  5 2016          Female Asian and pacific islander Emma                 99     4
    ##  6 2016          Female Asian and pacific islander Mia                  79     5
    ##  7 2016          Female Asian and pacific islander Charlotte            59     6
    ##  8 2016          Female Asian and pacific islander Sarah                57     7
    ##  9 2016          Female Asian and pacific islander Isabella             56     8
    ## 10 2016          Female Asian and pacific islander Hannah               56     8
    ## # … with 12,171 more rows

Produce a well-structured, reader-friendly table showing the rank in
popularity of the name “Olivia” as a female baby name over time, and
produce a similar table showing the most popular name among male
children over time.

``` r
Olivia_as_female_name = filter(popular_baby_names_df, childs_first_name == "Olivia", gender == "Female") %>% 
  select( -gender, -childs_first_name, -count) %>% 
  pivot_wider(
  names_from = "year_of_birth", 
  values_from = "rank") %>% 
  view()

Olivia_as_female_name
```

    ## # A tibble: 4 × 7
    ##   ethnicity                  `2016` `2015` `2014` `2013` `2012` `2011`
    ##   <chr>                       <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
    ## 1 Asian and pacific islander      1      1      1      3      3      4
    ## 2 Black non hispanic              8      4      8      6      8     10
    ## 3 Hispanic                       13     16     16     22     22     18
    ## 4 White non hispanic              1      1      1      1      4      2

``` r
Most_popular_male_name = filter(popular_baby_names_df, rank == 1, gender == "Male") %>%
  select(-gender, -count, -rank) %>% 
  pivot_wider(
  names_from = "year_of_birth", 
  values_from = "childs_first_name") %>% 
  view()

Most_popular_male_name
```

    ## # A tibble: 4 × 7
    ##   ethnicity                  `2016` `2015` `2014` `2013` `2012` `2011` 
    ##   <chr>                      <chr>  <chr>  <chr>  <chr>  <chr>  <chr>  
    ## 1 Asian and pacific islander Ethan  Jayden Jayden Jayden Ryan   Ethan  
    ## 2 Black non hispanic         Noah   Noah   Ethan  Ethan  Jayden Jayden 
    ## 3 Hispanic                   Liam   Liam   Liam   Jayden Jayden Jayden 
    ## 4 White non hispanic         Joseph David  Joseph David  Joseph Michael

Finally, for male, white non-hispanic children born in 2016, produce a
scatter plot showing the number of children with a name (y axis) against
the rank in popularity of that name (x axis).

``` r
Male_white_2016 = filter(popular_baby_names_df, gender == "Male", year_of_birth == 2016, ethnicity == "White non hispanic")

Male_white_2016
```

    ## # A tibble: 364 × 6
    ##    year_of_birth gender ethnicity          childs_first_name count  rank
    ##    <chr>         <chr>  <chr>              <chr>             <dbl> <dbl>
    ##  1 2016          Male   White non hispanic Joseph              261     1
    ##  2 2016          Male   White non hispanic Michael             260     2
    ##  3 2016          Male   White non hispanic David               255     3
    ##  4 2016          Male   White non hispanic Moshe               239     4
    ##  5 2016          Male   White non hispanic Jacob               236     5
    ##  6 2016          Male   White non hispanic James               231     6
    ##  7 2016          Male   White non hispanic Benjamin            219     7
    ##  8 2016          Male   White non hispanic Alexander           211     8
    ##  9 2016          Male   White non hispanic Daniel              196     9
    ## 10 2016          Male   White non hispanic Henry               196     9
    ## # … with 354 more rows

``` r
ggplot(Male_white_2016, aes(x = rank, y = count)) + geom_point() 
```

![](p8105_hw2_sc4935_files/figure-gfm/unnamed-chunk-15-1.png)<!-- -->

Finished homework.
